language: objective-c

branches:
  only:
    - master

xcode_project: NotifyDemo.xcodeproj
xcode_scheme: NotifyDemoTests
osx_image: xcode9
xcode_sdk: iphonesimulator10.0

script:
  - xcodebuild test -project NotifyDemo.xcodeproj -scheme "NotifyDemo" -destination "platform=iOS Simulator,name=iPhone 6s"
